### ISSUE TITLE
File path bug.

### ISSUE THREAD

**Issue by his4000** [silagokth/vesyla-1#2]
Hello,

When I compile the file which has some macro syntax, there is a bug according to the path.

For example,

Works : ./vesyla -o *\<Relative file path for output\>* *\<Relative file path for matlab code\>* *\<Relative json file path used in macro syntax\>*

Doesn't work : ./vesyla -o *\<Absolute file path for output\>* *\<Absolute file path for matlab code\>* *\<Absolute json file path used in macro syntax\>*

I add my file tree.
```
$PROJECT ROOT/
    |- output/
    |- src/
         |- matlab code
         |- json file
```

**Comment by herenvarno** [comment]
It's caused by inja library. Inja library is designed in the way that while instantiating an Environment object, input file path and output file path need to be specified. All the files used by inja library will be relative path respect to those specified file path for IO.

To fix the problem, I made vesyla to read the template file and json file and convert them to string and json object. Then those object is fed to render() function. Now absolute path is accepted.
